language: go

go:
  - "1.14"
  - "1.15"
  - "1.16"
  - tip

services:
  - postgresql

before_script:
  - psql -c 'CREATE USER planter;' -U postgres
  - psql -c 'CREATE DATABASE planter OWNER planter;' -U postgres

script:
  - go fmt ./...
  - go test -v
